application: #enter app name here
version: prototype
runtime: python27
api_version: 1
threadsafe: true
module: default
skip_files:
- ^node_modules/.*$
- ^dev/.*$
handlers:
- url: /
  static_files: public/static/index.html
  upload: public/static/index.html
  secure: always

- url: /(page.*)
  static_files: public/static/index.html
  upload: public/static/index.html
  secure: always

- url: /(.*)
  static_files: public/static/\1
  upload: public/static/(.*)
  secure: always
